export enum MessageSender {
  User = 'user',
  Lvachir = 'lvachir',
}

export interface ChatMessage {
  id: string;
  text: string;
  sender: MessageSender;
  timestamp: Date;
  loading?: boolean; // Indicates if this message is currently being generated by the AI
}
